west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.5.8

manifest:
  remotes:
    - name: cio-remote
      url-base: file:///home/gatzka/workspace/git
    - name: zephyr-remote
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: cio
      remote: cio-remote
      revision: master

    - name: zephyr
      remote: zephyr-remote
      revision: master
      west-commands: scripts/west-commands.yml

  self:
    path: bla

