west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.5.8

manifest:
  remotes:
    - name: cio-remote
      url-base: file:///home/gatzka/workspace/git

  projects:
    - name: cio
      remote: cio-remote
      revision: master

  self:
    path: bla

