west:
  url: https://github.com/zephyrproject-rtos/west
  revision: v0.5.7

manifest:
  remotes:
    - name: cio-remote
      url-base: file:///home/gatzka/workspace/git/cio/

  projects:
    - name: cio
      remote: cio-remote
      revision: master

